### ISSUE TITLE
[Bug] Usage of internal glibc header sys/cdefs.h

### ISSUE THREAD

**Issue by albap** [JuliaLang/openlibm#112]
Trying to compile Julia on a musl libc system reveals this bug on openlibm.
As instructed by [musl libc documentation](http://wiki.musl-libc.org/wiki/FAQ#Q:_I.27m_trying_to_compile_something_against_musl_and_I_get_error_messages_about_sys.2Fcdefs.h), I'm reporting the bug.

**Comment by tkelman** [comment]
Ah, I think this has already been fixed in 9a48c873869861582640ed12bfb8ed4ba8289dab, but Julia's still using a version of openlibm that's a little over a year old. We would need to test upgrading to latest master carefully on all platforms, since some functions were removed here that Julia might have actually needed.

**Comment by yuyichao** [comment]
> since some functions were removed here that Julia might have actually needed.

They should be added back now. Julia with openlibm git master passes all tests on linux.

**Comment by albap** [comment]
Nice!
> Julia with openlibm git master passes all tests on linux.

Can Julia start using the newest openlibm then?

**Comment by tkelman** [comment]
ref https://github.com/JuliaLang/openlibm/pull/85#issuecomment-153561513 and https://github.com/JuliaLang/julia/pull/13868
