### ISSUE TITLE
make ARCH=arm fails

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/openlibm#143]
Something is wrong in the `Make.inc`. The following fails:

```
viral@julia-arm:~/openlibm$ make ARCH=arm
Make.inc:151: *** No known generic arm cflags. Please specify arch type.  Stop.
```

**Comment by nalimilan** [comment]
`arm` isn't a specific enough architecture, so how would it work? E.g. `armv7-a` should work.

**Comment by yuyichao** [comment]
Closing since the error seems to added explicitly to avoid ppl making mistake when specifying a useless arch name.

FWIW, `arm` isn't a valid `-march` value for compiler, which makes sense since `arm` doesn't really specify an arch when you're already compiling for a ARM target. You also probably not want to compile for the most generic ARM instruction set either.

**Comment by ViralBShah** [comment]
BTW, this error occurs because this is how the julia build system tries  to build openlibm. So, perhaps something needs to be fixed on that side.
