### ISSUE TITLE
Constant(s) lack of precision

### ISSUE THREAD

**Issue by Kochise** [JuliaLang/openlibm#159]
```
k_cos.c : C1  =  4.16666666666666019037e-02, /* 0x3FA55555, 0x5555554C */
k_cosf.c : C1  =  0x155553e1053a42.0p-57,   /*  0.0416666233237390631894 */
```

0.0416666[**666666666019037**] vs 0.0416666[**233237390631894**]

```
k_sin.c : S1  = -1.66666666666666324348e-01, /* 0xBFC55555, 0x55555549 */
k_sinf.c : S1 = -0x15555554cbac77.0p-55,   /* -0.166666666416265235595 */
```

-0.166666666[**666666324348**] vs -0.166666666[**416265235595**]

These are just a couple of example but the problem spreads across all files. Is that really serious to have such volatility among mathematical constants, or supposed to be ? How can we expect to have an accurate precision for those constants, not only being duplicated all over the place, but also lacks consistency ?

Provide these constants as define or in an external constant array (like in 'math_private.c') shared between all files.

**Comment by Kochise** [comment]
Let's take the amazing PI for instance, just remember its digits :

3.141592653589793238462643383279502884197169399

```
e_acos.c : pi =  3.141592653589793[**11600**]e+00, /* 0x400921FB, 0x54442D18 */
e_acosf.c : pi =  3.141592[**5026**]e+00, /* 0x40490fda */
e_atan2f.c : pi      = 3.141592[**7410**]e+00; /* 0x40490fdb */
```

Round it up to 3.1415 if you think that's enough precision.

**Comment by StefanKarpinski** [comment]
Much of the code in openlibm comes from different original sources. A PR to make constants consistent would be welcomed, provided it's accompanied with sufficient testing to show that changing the constants does not make the accuracy of functions that use them worse. Of course, it _shouldn't_, but you never know why the original author deviated from the true value of a constant.

**Comment by Kochise** [comment]
Comments ?

**Comment by simonbyrne** [comment]
These are the coefficients of the [minimax polynomial approximations](https://en.wikipedia.org/wiki/Minimax_approximation_algorithm) of different degrees: though the common coefficients should be similar (since they're analytic functions), there is no reason they should be the same

**Comment by simonbyrne** [comment]
Regarding the `pi` issue: `atan2f` is using the closest `float` to pi, so that's correct. It probably doesn't use the actual value in order to reduce the chance that the C compiler parses it incorrectly: not such an issue these days, but certainly was in the 90s.

The `acosf` case is more interesting: my guess is that it is so that this line
https://github.com/JuliaLang/openlibm/blob/0598080ca09468490a13ae393ba17d8620c1b201/src/e_acosf.c#L45
will trigger the inexact floating point flag on any compilers that care to implement it correctly.

This code has a long and proven history, so I think we should apply the principle of [Chesterton's fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton.27s_fence) before making changes.

**Comment by Kochise** [comment]
Anyway, comments would have been welcomed cheerfully.

**Comment by StefanKarpinski** [comment]
Absolutely!
