### ISSUE TITLE
test-double failure on i686

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/openlibm#55]
We're seeing this failure when running test-double on a 32-bit Fedora VM. This test passes on 64-bit.
```
./test-double
testing double (without inline functions)
FP-Stack wrong after test exp (-0) == 1 (2, should be 0)
Test suite completed:
  1148 test cases plus 962 tests for exception flags executed.
  1 errors occurred.
```

**Comment by ViralBShah** [comment]
I wonder if using the system provided headers in #77 will address this without us needing to dig too deep.

**Comment by ViralBShah** [comment]
I have an Ubuntu 32 bit VM where all tests pass. Do I need a 32 bit cpu for reproducing this?

**Comment by ViralBShah** [comment]
Does the same apply for clang?

**Comment by nalimilan** [comment]
I haven't tried clang. Anyway it sounds plausible that you need a 32-bit CPU to reproduce.

**Comment by eschnett** [comment]
On 32-bit systems, the floating point stack is used to return `double` values from functions. 64-bit system use an SSE register instead. I've seen errors like this in the past when there was an error in a function prototype. For example, if a `double` function is somewhere else declared with an `int` prototype (or there is no prototype so the compiler assumes `int`), then the caller doesn't pop the result from the FP stack.

Can you find out which of the `exp` implementations is called from the test suite? From the description above, it could be either `i387/e_exp.S` or `bsdsrc/b_exp.c` or `src/e_exp.c`.

**Comment by nalimilan** [comment]
@eschnett I can't find any occurrence of `src/e_exp.c` in the build log, so it looks like it's one of the two others, which are both included into the final .so file AFAICT.

What's interesting is that `test-float` succeeds, and it uses the exact same code, except for a few macros. This one is particularly interesting: `#define FLOAT float` vs. `#define FLOAT double`. Could this kind of error appear if a double is wrongly considered as a float?

BTW, building with clang gives many more warnings:
https://kojipkgs.fedoraproject.org//work/tasks/370/8790370/build.log

**Comment by eschnett** [comment]
If I recall, single-precision values are returned in a register (`%eax`?), not on the stack, so they would not lead to this problem.

The `#define FLOAT ...` macros seem harmless at first sight. But yes, if a double-returning function is accidentally declared as returning a float, this would lead exactly to this kind of problem.

The Clang build log points to several harmless and four potentially troublesome issues. The "implicit declaration"s of `powl`, `expl`, `logl`, and `__fpgetprec` may cause problems, but they are related to complex numbers and long double, so probably not relevant here.

**Comment by eschnett** [comment]
I was wrong above. Single-precision values are also returned on the FP stack. Mixing `float`/`double` should thus not be an issue.

The routine that checks the floating-point stack (`fpstack_test`, file `libm-test.c` in openelibm) tries to remember the old stack position. "Tries", because the old stack position is never properly initialized.

I am getting curious about this error. I wonder whether you could make the compiled 32-bit `libopenlibm.a` as well as `test-double` accessible to me?

**Comment by nalimilan** [comment]
Sure. You can get them from the RPMs at http://koji.fedoraproject.org/koji/taskinfo?taskID=8792214

I've put the tests in /usr/bin/openlibm-test/ of the -devel package. The library is in the main package. (In case you're a pure .deb guy, you can open the .rpm as .tar.gz, no need to install them.)

**Comment by eschnett** [comment]
The file `test-double` has been stripped. That makes it impossible to analyze it. Can you produce a non-stripped executable? I don't necessarily need debug information, but I do need the names of the functions.

**Comment by nalimilan** [comment]
This one should be better: http://koji.fedoraproject.org/koji/taskinfo?taskID=8795157

**Comment by eschnett** [comment]
The code in the file `test-double` looks fine.

I'm now not sure that the FP stack pointer should retain its value in between function calls. The FP "stack" is not, after all, actually a stack. Maybe the test itself is over-zealous, and is broken by today's more clever FP optimizers? If you disable the stack test (the function `fpstack_test`), does everything else then work fine?

**Comment by nalimilan** [comment]
With `fpstack_test` made a no-op all tests pass.

But if the FP-Stack testing logic is broken, it's weird that only `exp` fails. Anyway you're much more knowledgeable than me on that front. If you can't find any reason for this stuff, we can disable it.

**Comment by eschnett** [comment]
I saw reports from two different `exp` tests -- either the first or the second test seemed to fail. I don't know why there should be this difference.

I've looked at the Intel 32-bit ABI and how floating-point arguments are passed. The ABI document is a bit "fluffy", not like a standard should be, but if you read in between the lines, it's clear that the FP stack in not preserved by a function call, and thus a function has no reason to put the stack into any particular state before returning. Since the "stack" is actually just a ring list, there also doesn't seem to be a reason to put the "stack pointer" into a particular state. So I think we're safe. But I can't point to documentation to prove it.

**Comment by nalimilan** [comment]
Though while googling I've found that icc accepts `-fp-stack-check`, which is described as:
```
              Tells the compiler to generate  extra  code  after  every
              function  call to ensure that the floating-point stack is
              in the expected state.
```
http://geco.mines.edu/guide/icc.html

Not sure what this really means, but doesn't it imply there's a reliable way of checking the FP stack state?

**Comment by eschnett** [comment]
The i386 (32 bit) ABI specifies that the FP stack must be empty before and after a function call. This is different in the x86-64 (64 bit) ABI, which only states that all FP stack slots are caller-save. I believe the i386 rule exists to allow implementations to use the FP stack analogous to a real stack, by catching FP stack over- and under-flows and saving/restoring FP stack entries in the trap handler. (At least that's what Kahan suggested 25 years ago.) I don't know of a Unix compiler that does this, nor does it make sense given the i386 ABI.

What may be happening is that modern compilers ignore this part of the i386 ABI (stack must be empty) since it can save instructions that would otherwise be necessary to pop unused elements from the FP stack.

What the FP stack check in openlibm should do is check the FP stack pointer right before and after the call to `exp`. What it does instead is check it after analyzing the returned value, which executes a host of unrelated FP instructions that deal with exceptions, infs, nans, etc. My guess is that some of the functions used in this analysis code don't respect the FP stack structure.

**Comment by nalimilan** [comment]
OK, if you can find a fix then go ahead...

(FWIW, I've tried making `exp_test` a no-op, and indeed all tests pass. OTOH, if I remove the first line, which tests `exp(0.)`, then the second one, which tests `exp(-0.)` fails. So it looks like only the first FP-Stack failure is reported for each function.)

**Comment by eschnett** [comment]
No, all FP stack failures are reported.

**Comment by nalimilan** [comment]
What? I'm only seeing one failure at a time in the logs I showed above. And see for example this one where I removed the line testing `exp(0)`: https://kojipkgs.fedoraproject.org//work/tasks/6710/8806710/build.log

Anyway, I'm not sure it really matters.

**Comment by nalimilan** [comment]
So, what should we do?

@eschnett You seem to be the most knowledgeable person around, so please choose the solution you find the most reasonable.

**Comment by eschnett** [comment]
I say disable the stack check. I assume that modern compilers ignore this part of the ABI.

**Comment by nalimilan** [comment]
So, something as radical as https://github.com/JuliaLang/openlibm/pull/87?

**Comment by eschnett** [comment]
Yes.
